all:
  hosts:
    server-01:
      ansible_user: dashaakinshinachechulina
      ansible_host: 10.10.99.1
    server-02:
      ansible_user: dashaakinshinachechulina
      ansible_host: 10.10.99.6
    server-03:
      ansible_user: admin
      ansible_host: 10.10.99.18
