ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM registry.rebrainme.com/devops_users_repos/965/do-30/kibana:${ELASTIC_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
