ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM registry.rebrainme.com/devops_users_repos/965/do-30/logstash:${ELASTIC_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
