- name: Create Database in Postgres
  postgresql_db:
    name: "{{ item.name }}"
    lc_collate: "{{ item.lc_collate | default('en_US.UTF-8') }}"
    lc_ctype: "{{ item.lc_ctype | default('en_US.UTF-8') }}"
    encoding: "{{ item.encoding | default('UTF-8') }}"
    template: "{{ item.template | default('template0') }}"
    conn_limit: "{{ item.conn_limit | default(500) }}"
    owner: "{{ item.owner | default('postgres') }}"
    port: "{{ percona_pgsql.postgres_port }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ percona_pgsql.psql_databases }}"
  become_user: postgres
  become: true
  tags: create_database_pgsql
  when: percona_pgsql.replication|bool == False or percona_pgsql.role == 'master'
