- name: Setting facts for master
  set_fact:
    master_address: "{{ percona_pgsql.master_address }}"

- name: Setting facts for slave
  set_fact:
    slave_address: "{{ percona_pgsql.slave_address }}"

- name: Update configuration to "server.conf"
  blockinfile:
    dest: /etc/postgresql/{{ percona_pgsql.version }}/main/server.conf
    block: |
      listen_addresses = '{{ ansible_default_ipv4.address }}'

- name: Add new configuration to "pg_hba.conf"
  blockinfile:
    dest: /etc/postgresql/{{ percona_pgsql.version }}/main/pg_hba.conf
    block: |
      host    all             all                      0.0.0.0/0                md5
      host    replication     {{ percona_pgsql.replica_user }}       {{ item }}/32            md5
  with_items: "{{ percona_pgsql.slave_address }}"
  when:
    - percona_pgsql.role == 'master'

- name: Restart postgresql
  service:
    name: postgresql
    state: restarted
  when:
    - percona_pgsql.role == 'master'

- name: Create replica user in postgres master
  postgresql_user:
    db: postgres
    name: "{{ percona_pgsql.replica_user }}"
    password: "{{ percona_pgsql.replica_pass }}"
    role_attr_flags: REPLICATION
  when:
    - percona_pgsql.role == 'master'
  become: true
  become_user: postgres

- name: Make Backup of Postgres Config on slave
  command: mv main/ main-bkp
  args:
    chdir: /var/lib/postgresql/{{ percona_pgsql.version }}
  when:
    - percona_pgsql.role == 'master'

- name: Add master backup on slavve
  shell: |
   export PGPASSWORD="{{ percona_pgsql.replica_pass }}" && /usr/bin/pg_basebackup -h \
   {{ percona_pgsql.master_address }} -U {{ percona_pgsql.replica_user }} -D \
   /var/lib/postgresql/{{ percona_pgsql.version }}/main -P -v -R 2>&1
  become_user: postgres
  become: true
  when:
    - percona_pgsql.role == 'master'

- name: Change Permission of config on slave
  file:
    path: /var/lib/postgresql/{{ percona_pgsql.version }}/main/
    owner: postgres
    group: postgres
    mode: 0700
    state: directory

- name: Restart postgresql
  service:
    name: postgresql
    state: restarted
  when:
    - percona_pgsql.role == 'master'
